-- 1. what is the total revenue generated by male vs female customers?
	
	select gender,sum(purchase_amount) as revenue
	from customer
	group by gender

-----------------------------------------------------------------------------

-- 2. which customer used a discount but still spend more than the average purchase amount?


	select customer_id,purchase_amount 
	from customer 
	where (discount_applied='Yes') and purchase_amount >= (select avg(purchase_amount) from customer)

-------------------------------------------------------------------------------

-- 3. which are the top 5 products with the highest average review rating?

	select item_purchased, round(avg(review_rating::numeric),2)
	from customer
	group by item_purchased 
	order by avg(review_rating) desc
	limit 5

----------------------------------------------------------------------------------

-- 4. comare the average purchase amount between standard and express shipping
	
	select shipping_type, Round(avg(purchase_amount),2)
	from customer
	where shipping_type='Express' or shipping_type='Standard'
	group by shipping_type

----------------------------------------------------------------------------------

-- 5. do subscribe customers spend more? compare average spend and total revenue between subscribe and non-subscribers

	select subscription_status,
	count(customer_id) as total_customers, 
	round(avg(purchase_amount),2) as avg_spend,
	round(sum(purchase_amount),2) as total_renue
	from customer
	group by subscription_status
-------------------------------------------------------------------------------------


-- 6. which 5 product have highest percentage of purchases with discount applied?

	select item_purchased, 
	round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/ count(*),2) as discount_rate
	from customer
	group by item_purchased
	order by discount_rate desc
	limit 5
---------------------------------------------------------------------------------

-- 7. segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment

	
with customer_type as(
	select customer_id, previous_purchases,
	case
		when previous_purchases= 1 then 'New'
		when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment , count(*) as "number of customers"
from customer_type
group by customer_segment


------------------------------------------------------------------------------------

-- 8. what are the top 3 most purchased product within each category


select category, item_purchased, count(customer_id) as count
from customer
group by item_purchased, category
order by count desc 
limit 10

-------------------------------------------------------------------------------

-- 9. are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?


select subscription_status, count(customer_id)
from customer
where previous_purchases>5
group by subscription_status

--------------------------------------------------------------------------------
-- 10. what are the revenue contributin of each age groups?

select age_group, count(customer_id),sum(purchase_amount) as total
from customer
group by age_group
order by total desc










